version: "3"

services:
  web:
    source: .
    start: cd web && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 300 app:app
    variables:
      PYTHONPATH: /app
      WEB_CONCURRENCY: 2
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    source: .
    start: cd web && python worker.py
    variables:
      PYTHONPATH: /app
      RQ_QUEUE: default
    depends_on:
      - redis

  scheduler:
    source: .
    start: cd web && python schedule_runner.py --interval 300
    variables:
      PYTHONPATH: /app
    depends_on:
      - redis
      - web

  redis:
    image: redis:7-alpine
    restart_policy:
      condition: on-failure
      max_attempts: 3
