name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        # 테스트에 필요한 최소한의 패키지만 설치
        # test_minimal.py는 외부 의존성이 없으므로 pytest 관련 패키지만 필요
        python -m pip install pytest pytest-cov pytest-mock
    
    - name: Run minimal tests
      run: |
        # Run tests that don't require external dependencies
        python -m pytest tests/test_minimal.py -v
    
    # 다른 테스트는 필요에 따라 여기에 추가 