name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  minimal_tests:
    name: Run Minimal Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov pytest-mock
    
    - name: Run minimal test
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        # 외부 의존성 없이 실행 가능한 기본 테스트
        python -m pytest tests/test_minimal.py -v
        
  # 참고: code-quality.yml 워크플로우에서 코드 품질 검사(Black)를 실행합니다.
  # 이 CI 워크플로우는 테스트에만 집중합니다.
  
  # 향후 안정화된 후 전체 테스트 추가 예정입니다.
  
  # 향후 다른 테스트를 추가할 경우를 위한 작업 예시
  # full_tests:
  #   name: Run Full Test Suite
  #   runs-on: ubuntu-latest
  #   needs: minimal_tests
  #   
  #   steps:
  #   - uses: actions/checkout@v4
  #   
  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.10'
  #   
  #   - name: Install all dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install -r requirements.txt
  #       python -m pip install pytest pytest-cov pytest-mock
  #   
  #   - name: Set up test environment
  #     run: |
  #       mkdir -p output
  #       # 필요한 환경 변수 설정
  #       echo "GEMINI_API_KEY=dummy_key_for_testing" >> $GITHUB_ENV
  #       echo "SERPER_API_KEY=dummy_key_for_testing" >> $GITHUB_ENV
  #   
  #   - name: Run full test suite
  #     env:
  #       PYTHONPATH: ${{ github.workspace }}
  #     run: |
  #       # 전체 테스트 실행 또는 개별 테스트 지정 가능
  #       # python -m pytest tests/ 