name: Code Quality & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 블랙 포맷팅과 기본 테스트에 필요한 의존성 설치
        pip install black pytest pytest-cov pytest-mock
        # 테스트 모킹에 필요한 추가 패키지 설치
        pip install python-dotenv
    
    - name: Check formatting with Black
      run: |
        black --check newsletter
        black --check tests
      continue-on-error: false
    
    - name: Create output directory for tests
      run: mkdir -p output
    
    - name: Run minimal tests only
      env:
        PYTHONPATH: ${{ github.workspace }}
        # 테스트 실행에 필요한 환경 변수 설정
        MOCK_LANGCHAIN: "true" 
        MOCK_GENAI: "true"
      run: |
        # 외부 의존성이 필요 없는 테스트만 실행
        python -m pytest tests/test_minimal.py tests/test_isolate_tools.py -v
    
    # 나중에 전체 테스트와 커버리지를 다시 활성화할 수 있음
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: ./coverage.xml
    #     fail_ci_if_error: false
