name: Code Quality & Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install the package in development mode without dependencies (they're already installed from requirements.txt)
        pip install -e . --no-deps
    
    - name: Check formatting with Black
      run: |
        black --check newsletter
        black --check tests
      continue-on-error: false
    
    - name: Create output directory for tests
      run: mkdir -p output
    
    - name: Run tests with pytest and coverage
      env:
        # Set environment variables for tests to run without requiring external credentials
        GEMINI_API_KEY: "dummy_key_for_testing"
        SERPER_API_KEY: "dummy_key_for_testing"
        PYTHONPATH: ${{ github.workspace }}
        # Set environment variables to prevent gRPC errors
        GRPC_DNS_RESOLVER: "native"
        GRPC_POLL_STRATEGY: "epoll1"
        # Use our mock modules
        PYTEST_PYTHONPATH: ${{ github.workspace }}/tests
      run: |
        # Only run the minimal test that doesn't have external dependencies
        python -m pytest tests -v --cov=newsletter --cov-report=xml --cov-report=term --cov-fail-under=80
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
