name: Code Quality & Basic Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Formatting & Basic Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        # 코드 품질 확인과 기본 테스트에 필요한 최소한의 패키지만 설치
        pip install black pytest pytest-cov pytest-mock
    
    - name: Check formatting with Black
      run: |
        black --check newsletter
        black --check tests
      continue-on-error: false
    
    - name: Create output directory if needed
      run: mkdir -p output
    
    - name: Run basic standalone tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        # 외부 의존성이 전혀 필요 없는 독립 테스트만 실행
        # tests/test_minimal.py는 독립적인 HTML 마커 제거 함수만 테스트합니다
        python -m pytest tests/test_minimal.py -v
    
    # 참고: 나중에 전체 테스트와 커버리지를 다시 활성화할 때는
    # 완전한 의존성 설치와 적절한 모킹 전략이 필요합니다.
