name: Test Tools and Dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-imports:
    name: Test Module Imports
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    
    - name: Debug module imports
      run: |
        # Create a script to test imports
        cat > test_imports.py << 'EOL'
        import sys
        import os
        
        # Mock modules before imports
        import unittest.mock
        from unittest.mock import Mock, patch
        
        # Create mock modules
        mock_modules = {
            "google.generativeai": Mock(),
            "google.generativeai.caching": Mock(),
            "langchain_google_genai": Mock(),
            "langchain_google_genai.chat_models": Mock(),
        }
        
        # Patch sys.modules
        with patch.dict(sys.modules, mock_modules):
            print("Patched modules successfully")
            try:
                from newsletter.tools import clean_html_markers
                print("Successfully imported clean_html_markers from newsletter.tools")
            except ImportError as e:
                print(f"Error importing from newsletter.tools: {e}")
        
        print("Test completed")
        EOL
        
        # Run the test script
        python test_imports.py
        
    - name: Run test_tools.py
      env:
        PYTHONPATH: ${{ github.workspace }}
        GEMINI_API_KEY: "dummy_key_for_testing"
        SERPER_API_KEY: "dummy_key_for_testing"
      run: |
        mkdir -p output
        python -m pytest tests/test_tools.py -v 